### ISSUE TITLE
Help rendering syntax line number highlighting with theme

### ISSUE THREAD

**Issue by andyfeller** [athackst/jekyll-theme-profile#58]
**Nice to meet you, @athackst, thank you for putting this theme together!** ✨

I came across your theme and would love to use it for my own personal site.  However I hoped you could take a look at some weird behavior I saw around CSS styling for syntax highlighting when line numbers were involved. 🙇

## Problem

As you can see in the following screenshot, using `markdown: kramdown` and enabling line numbers causes some weird stylistic changes:

![Image](https://github.com/athackst/jekyll-theme-profile/assets/2089743/a8cde96e-c7d0-44be-acc5-9389d83897f2)

**Branch:** https://github.com/andyfeller/andyfeller.github.io/tree/2nd-attempt
**_config:** https://github.com/andyfeller/andyfeller.github.io/blob/0ddfc8f3c881743ee22f3dcb332c48ec7bc60ef6/docs/_config.yml#L27-L40

```yaml
# Build settings
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts: # Rouge Options › https://github.com/jneen/rouge#full-options
    css_class: highlight
    # default_lang: console
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

```

Any suggestions? 🙇
